import './globals.css';

import { Montserrat } from 'next/font/google';
import localFont from 'next/font/local';

import Header from '@/components/Header';
import Providers from '@/provider/Provider';

import type { Metadata } from 'next';

const montserrat = Montserrat({ subsets: ['latin'], display: 'swap', variable: '--font-montserrat' });
// const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' });

const myFont = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${myFont.className} ${montserrat.variable}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
        <div id="modal-portal"></div>
      </body>
    </html>
  );
}
